networks:
  vault-net:
    driver: bridge
    external: false

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.home.tm"
    volumes:
      - ./data/:/data/
    networks:
      - vault-net
    security_opt:
      - no-new-privileges:true

  nginx-proxy:
    image: nginx:latest
    container_name: nginx_vault
    restart: unless-stopped
    networks:
      - vault-net
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Path to SSL certificates
      - ./logs/nginx/:/var/log/nginx/ # For logging (optional)
    security_opt:
      - no-new-privileges:true
