networks:
  vault-net:
    driver: bridge
    external: false

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.home.tm"
    volumes:
      - ./data/:/data/
    networks:
      - vault-net
#    ports:
#      - 8080:80
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:80/"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 90s
#    depends_on:
#      nginx-proxy:
#        condition: service_healthy
    security_opt:
      - no-new-privileges:true

  nginx-proxy:
    image: nginx:latest
    container_name: nginx_vault
    restart: unless-stopped
    networks:
      - vault-net
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Path to SSL certificates
      - ./logs/nginx/:/var/log/nginx/ # For logging (optional)
#    healthcheck:
#      test: ["CMD", "/usr/bin/check-health"]
#      interval: 10s
#      timeout: 3s
#      retries: 3
#      start_period: 90s
    security_opt:
      - no-new-privileges:true
