global_defs {
    router_id <BACKUP>
}

vrrp_script chk_dns {
    script "/usr/bin/nc -z 127.0.0.1 53"
    interval 3
    timeout 2
    fall 3
    rise 2
    weight -20
}

vrrp_instance VI_1 {
    state BACKUP
    interface <INTERFACE>
    virtual_router_id <UNIQUE_ID>
    priority 100
    advert_int 1

    unicast_src_ip <BACKUP_IP>
    unicast_peer {
        <MASTER_IP>
    }

    authentication {
        auth_type PASS
        auth_pass <AUTH_PASSWORD>
    }

    virtual_ipaddress {
        <VIRTUAL_IP>
    }

    track_script {
        chk_dns
    }

    preempt_delay 5
}
